### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress-plugins/classicpress-seo#146]
Following: https://forums.classicpress.net/t/help-test-php-8-0-compatibility-in-v1-5-0-rc1/4445/6

Update cpcompatibility failed: “Update Failed: Internal Server Error”, error log shows it’s Classic Seo causing it:
classicpress-seo/includes/module/class-manager.php(43): Classic_SEO\Helpers\Conditional::is_heartbeat()\n#3

After removing it cpcompatibility worked again and updated. Downloaded new version from CP SEO from the CP website, installation fails (changed username/domain in below). This is, I’d say, an essential plugin:

Fatal error: Uncaught TypeError: filter_var(): Argument #3 ($options) must be of type array|int, string given in /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/includes/helpers/class-param.php:56 Stack trace: #0 /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/includes/helpers/class-param.php(56): filter_var() #1 /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/classicpress-seo.php(314): Classic_SEO\Helpers\Param::request() #2 /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/classicpress-seo.php(188): Classic_SEO->init_actions() #3 /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/classicpress-seo.php(164): Classic_SEO->setup() #4 /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/classicpress-seo.php(440): Classic_SEO::get() #5 /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/classicpress-seo.php(444): cpseo() #6 /home/user/domains/userdomain.nl/public_html/cp/wp-admin/includes/plugin.php(2137): include(‘…’) #7 /home/user/domains/userdomain.nl/public_html/cp/wp-admin/plugins.php(176): plugin_sandbox_scrape() #8 {main} thrown in /home/user/domains/userdomain.nl/public_html/cp/wp-content/plugins/classicpress-seo/includes/helpers/class-param.php on line 56

**Comment by bahiirwa** [comment]
Sam eissue as #137
