### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by iSimsi** [ClassicPress-plugins/classicpress-seo#147]
PHP 8.0.26
Classic Press Version 1.5.0
Classic Seo Version 2.0.1

While activating the Plugin i get this error on my dev instance.

Fatal error: Uncaught TypeError: filter_var(): Argument #3 ($options) must be of type array|int, string given in /home/**/www/**/wp-content/plugins/classicpress-seo/includes/helpers/class-param.php:56 Stack trace: #0 /home/**/www/**/wp-content/plugins/classicpress-seo/includes/helpers/class-param.php(56): filter_var('error_scrape', 516, '') #1 /home/**/www/**/wp-content/plugins/classicpress-seo/classicpress-seo.php(314): Classic_SEO\Helpers\Param::request('action') #2 /home/**/www/**/wp-content/plugins/classicpress-seo/classicpress-seo.php(188): Classic_SEO->init_actions() #3 /home/**/www/**/wp-content/plugins/classicpress-seo/classicpress-seo.php(164): Classic_SEO->setup() #4 /home/**/www/**/wp-content/plugins/classicpress-seo/classicpress-seo.php(440): Classic_SEO::get() #5 /home/**/www/**/wp-content/plugins/classicpress-seo/classicpress-seo.php(444): cpseo() #6 /home/**/www/**/wp-admin/includes/plugin.php(2138): include('/home/**/...') #7 /home/**/www/**/wp-admin/plugins.php(176): plugin_sandbox_scrape('classicpress-se...') #8 {main} thrown in /home/**/www/**/wp-content/plugins/classicpress-seo/includes/helpers/class-param.php on line 56

**Comment by iSimsi** [comment]
Duplicate of https://github.com/ClassicPress-plugins/classicpress-seo/issues/137
